// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/follow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follow        bool                   `protobuf:"varint,1,opt,name=follow,proto3" json:"follow,omitempty"`
	FollowerId    int64                  `protobuf:"varint,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   int64                  `protobuf:"varint,3,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_proto_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *FollowRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_proto_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_proto_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{2}
}

func (x *Follow) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *Follow) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *Follow) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingId   int64                  `protobuf:"varint,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFollowersRequest) Reset() {
	*x = GetUserFollowersRequest{}
	mi := &file_proto_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFollowersRequest) ProtoMessage() {}

func (x *GetUserFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetUserFollowersRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserFollowersRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *GetUserFollowersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserFollowersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*User                `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	HasNext       bool                   `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFollowersResponse) Reset() {
	*x = GetUserFollowersResponse{}
	mi := &file_proto_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFollowersResponse) ProtoMessage() {}

func (x *GetUserFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetUserFollowersResponse) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserFollowersResponse) GetFollowers() []*User {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *GetUserFollowersResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *GetUserFollowersResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserFollowersResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetUserFollowingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFollowingsRequest) Reset() {
	*x = GetUserFollowingsRequest{}
	mi := &file_proto_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFollowingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFollowingsRequest) ProtoMessage() {}

func (x *GetUserFollowingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFollowingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserFollowingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserFollowingsRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *GetUserFollowingsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserFollowingsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetUserFollowingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followings    []*User                `protobuf:"bytes,1,rep,name=Followings,proto3" json:"Followings,omitempty"`
	HasNext       bool                   `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFollowingsResponse) Reset() {
	*x = GetUserFollowingsResponse{}
	mi := &file_proto_follow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFollowingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFollowingsResponse) ProtoMessage() {}

func (x *GetUserFollowingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFollowingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserFollowingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserFollowingsResponse) GetFollowings() []*User {
	if x != nil {
		return x.Followings
	}
	return nil
}

func (x *GetUserFollowingsResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *GetUserFollowingsResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserFollowingsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

var File_proto_follow_proto protoreflect.FileDescriptor

const file_proto_follow_proto_rawDesc = "" +
	"\n" +
	"\x12proto/follow.proto\x12\rfollowservice\"k\n" +
	"\rFollowRequest\x12\x16\n" +
	"\x06follow\x18\x01 \x01(\bR\x06follow\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x03 \x01(\x03R\vfollowingId\"*\n" +
	"\x0eFollowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\\\n" +
	"\x06Follow\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"j\n" +
	"\x17GetUserFollowersRequest\x12!\n" +
	"\ffollowing_id\x18\x01 \x01(\x03R\vfollowingId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"O\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"\x96\x01\n" +
	"\x18GetUserFollowersResponse\x121\n" +
	"\tfollowers\x18\x01 \x03(\v2\x13.followservice.UserR\tfollowers\x12\x19\n" +
	"\bhas_next\x18\x02 \x01(\bR\ahasNext\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"i\n" +
	"\x18GetUserFollowingsRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x99\x01\n" +
	"\x19GetUserFollowingsResponse\x123\n" +
	"\n" +
	"Followings\x18\x01 \x03(\v2\x13.followservice.UserR\n" +
	"Followings\x12\x19\n" +
	"\bhas_next\x18\x02 \x01(\bR\ahasNext\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor2\xa9\x02\n" +
	"\rFollowService\x12K\n" +
	"\fToggleFollow\x12\x1c.followservice.FollowRequest\x1a\x1d.followservice.FollowResponse\x12c\n" +
	"\x10GetUserFollowers\x12&.followservice.GetUserFollowersRequest\x1a'.followservice.GetUserFollowersResponse\x12f\n" +
	"\x11GetUserFollowings\x12'.followservice.GetUserFollowingsRequest\x1a(.followservice.GetUserFollowingsResponseB\fZ\n" +
	"./proto/pbb\x06proto3"

var (
	file_proto_follow_proto_rawDescOnce sync.Once
	file_proto_follow_proto_rawDescData []byte
)

func file_proto_follow_proto_rawDescGZIP() []byte {
	file_proto_follow_proto_rawDescOnce.Do(func() {
		file_proto_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_follow_proto_rawDesc), len(file_proto_follow_proto_rawDesc)))
	})
	return file_proto_follow_proto_rawDescData
}

var file_proto_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_follow_proto_goTypes = []any{
	(*FollowRequest)(nil),             // 0: followservice.FollowRequest
	(*FollowResponse)(nil),            // 1: followservice.FollowResponse
	(*Follow)(nil),                    // 2: followservice.Follow
	(*GetUserFollowersRequest)(nil),   // 3: followservice.GetUserFollowersRequest
	(*User)(nil),                      // 4: followservice.User
	(*GetUserFollowersResponse)(nil),  // 5: followservice.GetUserFollowersResponse
	(*GetUserFollowingsRequest)(nil),  // 6: followservice.GetUserFollowingsRequest
	(*GetUserFollowingsResponse)(nil), // 7: followservice.GetUserFollowingsResponse
}
var file_proto_follow_proto_depIdxs = []int32{
	4, // 0: followservice.GetUserFollowersResponse.followers:type_name -> followservice.User
	4, // 1: followservice.GetUserFollowingsResponse.Followings:type_name -> followservice.User
	0, // 2: followservice.FollowService.ToggleFollow:input_type -> followservice.FollowRequest
	3, // 3: followservice.FollowService.GetUserFollowers:input_type -> followservice.GetUserFollowersRequest
	6, // 4: followservice.FollowService.GetUserFollowings:input_type -> followservice.GetUserFollowingsRequest
	1, // 5: followservice.FollowService.ToggleFollow:output_type -> followservice.FollowResponse
	5, // 6: followservice.FollowService.GetUserFollowers:output_type -> followservice.GetUserFollowersResponse
	7, // 7: followservice.FollowService.GetUserFollowings:output_type -> followservice.GetUserFollowingsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_follow_proto_init() }
func file_proto_follow_proto_init() {
	if File_proto_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_follow_proto_rawDesc), len(file_proto_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_follow_proto_goTypes,
		DependencyIndexes: file_proto_follow_proto_depIdxs,
		MessageInfos:      file_proto_follow_proto_msgTypes,
	}.Build()
	File_proto_follow_proto = out.File
	file_proto_follow_proto_goTypes = nil
	file_proto_follow_proto_depIdxs = nil
}
