// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/feed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedRequest) Reset() {
	*x = GetUserFeedRequest{}
	mi := &file_proto_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedRequest) ProtoMessage() {}

func (x *GetUserFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedRequest.ProtoReflect.Descriptor instead.
func (*GetUserFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserFeedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserFeedRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetUserFeedRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	PostTitle     string                 `protobuf:"bytes,2,opt,name=PostTitle,proto3" json:"PostTitle,omitempty"`
	PostContent   string                 `protobuf:"bytes,3,opt,name=PostContent,proto3" json:"PostContent,omitempty"`
	PostOwnerID   int64                  `protobuf:"varint,4,opt,name=PostOwnerID,proto3" json:"PostOwnerID,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	PostImageUrl  string                 `protobuf:"bytes,7,opt,name=post_image_url,json=postImageUrl,proto3" json:"post_image_url,omitempty"`
	LikeCount     int64                  `protobuf:"varint,8,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeed) Reset() {
	*x = UserFeed{}
	mi := &file_proto_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeed) ProtoMessage() {}

func (x *UserFeed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeed.ProtoReflect.Descriptor instead.
func (*UserFeed) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1}
}

func (x *UserFeed) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *UserFeed) GetPostTitle() string {
	if x != nil {
		return x.PostTitle
	}
	return ""
}

func (x *UserFeed) GetPostContent() string {
	if x != nil {
		return x.PostContent
	}
	return ""
}

func (x *UserFeed) GetPostOwnerID() int64 {
	if x != nil {
		return x.PostOwnerID
	}
	return 0
}

func (x *UserFeed) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserFeed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserFeed) GetPostImageUrl() string {
	if x != nil {
		return x.PostImageUrl
	}
	return ""
}

func (x *UserFeed) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type GetUserFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userfeeds     []*UserFeed            `protobuf:"bytes,1,rep,name=userfeeds,proto3" json:"userfeeds,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedResponse) Reset() {
	*x = GetUserFeedResponse{}
	mi := &file_proto_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedResponse) ProtoMessage() {}

func (x *GetUserFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedResponse.ProtoReflect.Descriptor instead.
func (*GetUserFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserFeedResponse) GetUserfeeds() []*UserFeed {
	if x != nil {
		return x.Userfeeds
	}
	return nil
}

func (x *GetUserFeedResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetUserFeedResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_feed_proto protoreflect.FileDescriptor

const file_proto_feed_proto_rawDesc = "" +
	"\n" +
	"\x10proto/feed.proto\x12\vfeedservice\"[\n" +
	"\x12GetUserFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xf8\x01\n" +
	"\bUserFeed\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x1c\n" +
	"\tPostTitle\x18\x02 \x01(\tR\tPostTitle\x12 \n" +
	"\vPostContent\x18\x03 \x01(\tR\vPostContent\x12 \n" +
	"\vPostOwnerID\x18\x04 \x01(\x03R\vPostOwnerID\x12\x1a\n" +
	"\bUserName\x18\x05 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x06 \x01(\tR\x04Name\x12$\n" +
	"\x0epost_image_url\x18\a \x01(\tR\fpostImageUrl\x12\x1c\n" +
	"\tLikeCount\x18\b \x01(\x03R\tLikeCount\"x\n" +
	"\x13GetUserFeedResponse\x123\n" +
	"\tuserfeeds\x18\x01 \x03(\v2\x15.feedservice.UserFeedR\tuserfeeds\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit2_\n" +
	"\vFeedService\x12P\n" +
	"\vGetUserFeed\x12\x1f.feedservice.GetUserFeedRequest\x1a .feedservice.GetUserFeedResponseB\fZ\n" +
	"./proto/pbb\x06proto3"

var (
	file_proto_feed_proto_rawDescOnce sync.Once
	file_proto_feed_proto_rawDescData []byte
)

func file_proto_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)))
	})
	return file_proto_feed_proto_rawDescData
}

var file_proto_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_feed_proto_goTypes = []any{
	(*GetUserFeedRequest)(nil),  // 0: feedservice.GetUserFeedRequest
	(*UserFeed)(nil),            // 1: feedservice.UserFeed
	(*GetUserFeedResponse)(nil), // 2: feedservice.GetUserFeedResponse
}
var file_proto_feed_proto_depIdxs = []int32{
	1, // 0: feedservice.GetUserFeedResponse.userfeeds:type_name -> feedservice.UserFeed
	0, // 1: feedservice.FeedService.GetUserFeed:input_type -> feedservice.GetUserFeedRequest
	2, // 2: feedservice.FeedService.GetUserFeed:output_type -> feedservice.GetUserFeedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_feed_proto_init() }
func file_proto_feed_proto_init() {
	if File_proto_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_proto = out.File
	file_proto_feed_proto_goTypes = nil
	file_proto_feed_proto_depIdxs = nil
}
