syntax = "proto3";
package postservice;

option go_package = "./proto/pb";




service LikeService {
    rpc ToggleLike(LikeRequest) returns (LikeResponse);
    rpc GetPostLikes(GetPostLikesRequest) returns (GetPostLikesResponse);
}


message LikeRequest {
   bool state = 1;
}

message LikeResponse {
    string message = 2;     
}


message User {

    string name = 1;
    string username = 2;

}


message GetPostLikesRequest {

    int64 post_id = 1;
    int64 limit = 2;
    string cursor = 3;


}

message GetPostLikesResponse {

    repeated User users = 1;
    string cursor = 2;
    bool has_next = 3;

}