syntax = "proto3";
import "google/protobuf/empty.proto";
package authservice;
option go_package = "./proto/pb";


service AuthService{
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Logout(google.protobuf.Empty) returns (LogoutResponse);
    rpc RefreshHandler(RefreshRequest) returns (RefreshResponse);
    rpc SearchUser(SearchUserRequest) returns (SearchUserResponse);
    rpc GetUserProfile(GetUserProfileRequest) returns (GetUserProfileResponse);
    rpc  GenerateUploadURL(GenerateUploadURLRequest) returns (GenerateUploadURLResponse);


}

message RegisterRequest{
    string name = 1;
    string username = 2;
    string email = 3;
    string password = 4;
}

message RegisterResponse{
    int64 id = 1;
    string name = 2;
    string username = 3;
    string email = 4;
    string access_token = 5;
    string refresh_token = 6;
    string profile_image_url = 7;
  
    
}

message LoginRequest{

    string username = 1;
    string password = 2;
}

message LoginResponse {
    int64 id =1;
    string message = 2;
    string username =3;
    string access_token = 4;
    string refresh_token = 5;
    int64 follower_count = 6;
    int64 following_count = 7;
    string profile_image_url = 8;

}

message LogoutRequest {

 
}

message LogoutResponse {
    string message = 1;

}

message RefreshRequest {

    string refresh_token = 1;
}

message RefreshResponse {
    string access_token = 1;
    string refresh_token = 2;
}


message User {
    
    int64 id = 1;
    string username = 2;
    string name = 3;
    
}

message SearchUserRequest {

    string username = 1;
    int64 limit = 2;
    string cursor = 3;

}

message SearchUserResponse {

    repeated User users = 1;
    string cursor = 2;
    bool has_next = 3;

}


message GetUserProfileRequest {

    int64 user_id = 1;



}

message GetUserProfileResponse {

    int64 id = 1;
    string username = 2;
    string name = 3;
    string profile_image_url = 4;
    int64 follower_count = 5;
    int64 following_count = 6;
    


}



message GenerateUploadURLRequest {

  string filename = 1;
  string content_type = 2;
  int64  user_id = 3;
}


message GenerateUploadURLResponse {

  string upload_url = 1;
  map<string, string> form_data = 2;

}