syntax = "proto3";
package postservice;

option go_package = "./proto/pb";


service PostService{

    rpc CreatePost(CreatePostRequest) returns (CreatePostResponse);
    rpc UpdatePost(UpdatePostRequest) returns (UpdatePostResponse);
    rpc DeletePost(DeletePostRequest) returns (DeletePostResponse);
    rpc ListPosts(ListPostsRequest) returns (ListPostsResponse);
    rpc GetUserPosts(GetUserPostRequest) returns (GetUserPostResponse);
    rpc  GenerateUploadURL(GenerateUploadURLRequest) returns (GenerateUploadURLResponse);

}

message Post{
    int64 id = 1;
    string title = 2;
    string content = 3;
    int64 user_id = 4;
    string post_image_url = 5;

}

message CreatePostRequest{
    int64 user_id = 1;
    string title = 2;
    string content = 3;
    string post_image_url = 4;

    

}

message CreatePostResponse {
    string post_id = 1;
    string title = 2;
    string content = 3;
    string post_image_url = 4;

}

message UpdatePostRequest{
    int64 post_id = 1;
    string title = 2;
    string content = 3;
    string post_image_url = 4;


}

message UpdatePostResponse{
    string status = 1;
    string message = 2;
    string post_image_url = 3;


}

message DeletePostRequest{

    int64 post_id = 1;

}

message DeletePostResponse{
    string status = 1;
    string message = 2;

}

message ListPostsRequest{


}
message ListPostsResponse {
  repeated Post posts = 1;

}


message GetUserPostRequest {

    int64 user_id = 1;
    int64 limit = 2;
    string cursor = 3;
}

message GetUserPostResponse {

  repeated Post posts = 1;
  string cursor = 2;
  bool has_next = 3;


}


message GenerateUploadURLRequest {

  string filename = 1;
  string content_type = 2;
  int64  user_id = 3;
}


message GenerateUploadURLResponse {

  string upload_url = 1;
  map<string, string> form_data = 2;

}