// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         bool                   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_proto_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_proto_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetPostLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostLikesRequest) Reset() {
	*x = GetPostLikesRequest{}
	mi := &file_proto_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesRequest) ProtoMessage() {}

func (x *GetPostLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesRequest.ProtoReflect.Descriptor instead.
func (*GetPostLikesRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{3}
}

func (x *GetPostLikesRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostLikesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPostLikesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetPostLikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostLikesResponse) Reset() {
	*x = GetPostLikesResponse{}
	mi := &file_proto_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesResponse) ProtoMessage() {}

func (x *GetPostLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesResponse.ProtoReflect.Descriptor instead.
func (*GetPostLikesResponse) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostLikesResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetPostLikesResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetPostLikesResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

var File_proto_like_proto protoreflect.FileDescriptor

const file_proto_like_proto_rawDesc = "" +
	"\n" +
	"\x10proto/like.proto\x12\vpostservice\"#\n" +
	"\vLikeRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\bR\x05state\"(\n" +
	"\fLikeResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\\\n" +
	"\x13GetPostLikesRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"r\n" +
	"\x14GetPostLikesResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.postservice.UserR\x05users\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext2\xa5\x01\n" +
	"\vLikeService\x12A\n" +
	"\n" +
	"ToggleLike\x12\x18.postservice.LikeRequest\x1a\x19.postservice.LikeResponse\x12S\n" +
	"\fGetPostLikes\x12 .postservice.GetPostLikesRequest\x1a!.postservice.GetPostLikesResponseB\fZ\n" +
	"./proto/pbb\x06proto3"

var (
	file_proto_like_proto_rawDescOnce sync.Once
	file_proto_like_proto_rawDescData []byte
)

func file_proto_like_proto_rawDescGZIP() []byte {
	file_proto_like_proto_rawDescOnce.Do(func() {
		file_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)))
	})
	return file_proto_like_proto_rawDescData
}

var file_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_like_proto_goTypes = []any{
	(*LikeRequest)(nil),          // 0: postservice.LikeRequest
	(*LikeResponse)(nil),         // 1: postservice.LikeResponse
	(*User)(nil),                 // 2: postservice.User
	(*GetPostLikesRequest)(nil),  // 3: postservice.GetPostLikesRequest
	(*GetPostLikesResponse)(nil), // 4: postservice.GetPostLikesResponse
}
var file_proto_like_proto_depIdxs = []int32{
	2, // 0: postservice.GetPostLikesResponse.users:type_name -> postservice.User
	0, // 1: postservice.LikeService.ToggleLike:input_type -> postservice.LikeRequest
	3, // 2: postservice.LikeService.GetPostLikes:input_type -> postservice.GetPostLikesRequest
	1, // 3: postservice.LikeService.ToggleLike:output_type -> postservice.LikeResponse
	4, // 4: postservice.LikeService.GetPostLikes:output_type -> postservice.GetPostLikesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_like_proto_init() }
func file_proto_like_proto_init() {
	if File_proto_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_like_proto_goTypes,
		DependencyIndexes: file_proto_like_proto_depIdxs,
		MessageInfos:      file_proto_like_proto_msgTypes,
	}.Build()
	File_proto_like_proto = out.File
	file_proto_like_proto_goTypes = nil
	file_proto_like_proto_depIdxs = nil
}
