// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: like/proto/like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         bool                   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_like_proto_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_like_proto_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_like_proto_like_proto protoreflect.FileDescriptor

const file_like_proto_like_proto_rawDesc = "" +
	"\n" +
	"\x15like/proto/like.proto\x12\vpostservice\"#\n" +
	"\vLikeRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\bR\x05state\"(\n" +
	"\fLikeResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2P\n" +
	"\vLikeService\x12A\n" +
	"\n" +
	"ToggleLike\x12\x18.postservice.LikeRequest\x1a\x19.postservice.LikeResponseB\fZ\n" +
	"./proto/pbb\x06proto3"

var (
	file_like_proto_like_proto_rawDescOnce sync.Once
	file_like_proto_like_proto_rawDescData []byte
)

func file_like_proto_like_proto_rawDescGZIP() []byte {
	file_like_proto_like_proto_rawDescOnce.Do(func() {
		file_like_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_proto_like_proto_rawDesc), len(file_like_proto_like_proto_rawDesc)))
	})
	return file_like_proto_like_proto_rawDescData
}

var file_like_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_like_proto_like_proto_goTypes = []any{
	(*LikeRequest)(nil),  // 0: postservice.LikeRequest
	(*LikeResponse)(nil), // 1: postservice.LikeResponse
}
var file_like_proto_like_proto_depIdxs = []int32{
	0, // 0: postservice.LikeService.ToggleLike:input_type -> postservice.LikeRequest
	1, // 1: postservice.LikeService.ToggleLike:output_type -> postservice.LikeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_like_proto_like_proto_init() }
func file_like_proto_like_proto_init() {
	if File_like_proto_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_proto_like_proto_rawDesc), len(file_like_proto_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_like_proto_goTypes,
		DependencyIndexes: file_like_proto_like_proto_depIdxs,
		MessageInfos:      file_like_proto_like_proto_msgTypes,
	}.Build()
	File_like_proto_like_proto = out.File
	file_like_proto_like_proto_goTypes = nil
	file_like_proto_like_proto_depIdxs = nil
}
